### ISSUE TITLE
Unsupported command .zip

### ISSUE THREAD

**Issue by maikelthedev** [Ceryn/i3msg-python#4]
When I'm trying to run this, I get this problem. 

Traceback (most recent call last):
  File "exampleqt.py", line 6, in <module>
    import i3msg as i3
  File "/home/maikel/.virtualenvs/pyqt/lib/python3.7/site-packages/i3msg/__init__.py", line 7, in <module>
    for k, v in zip(MSGS, range(len(MSGS))) + zip(EVENTS, range(len(EVENTS))):
TypeError: unsupported operand type(s) for +: 'zip' and 'zip

**Comment by maikelthedev** [comment]
It seems this is happening due to dated version in PyPi. Could you please update it?

Also your instructions are broken. You say

> Alternatively, you can download and put it where you need it:
> 
> cd /path/to/dependent/script.py
> wget https://raw.githubusercontent.com/Ceryn/i3msg-python/master/i3msg.py
> touch __init__.py

That will do nothing. 

What worked for me was to access the virtual env folder. Download there the file, then rename it to __init__.py. Touch command just creates empty files. 

So, if my folder is /home/me/.virtualenv/someenv/...../i3mg/__init__.py. This is what I'll have to do to make it work until you finally update the PyPI version. 

> rm /home/me/.virtualenv/someenv/...../i3mg/__init__.py
> wget https://raw.githubusercontent.com/Ceryn/i3msg-python/master/i3msg.py
> mv i3msg.py __init__.py
> echo 'Ceryn please update the PyPi repo'

and it works.
